### PR TITLE
Move `BloomFilter` module out of `Run` namespace and rename it to `Monkey`

### PR DESCRIPTION
**Pull request by jorisdral**

### CODE REVIEW

**Review by phadej — CHANGES_REQUESTED** [review]
I don't like this.

This module now mixes serialization code and some size calculations.

These are unrelated, and should stay in separate modules.

(

**Comment by jorisdral** [comment]
> I don't like this.
> 
> This module now mixes serialization code and some size calculations.
> 
> These are unrelated, and should stay in separate modules.
> 
> (

I suppose I could add a `Monkey` module. Is that what you had in mind?

**Comment by phadej** [comment]
> I suppose I could add a `Monkey` module. Is that what you had in mind?

Monkey sounds great!

**Review by dcoutts — APPROVED** [review]
LGTM!

**Pull request merged**
