### PR TITLE
Simplify pre-commit scripts.

### PR DESCRIPTION
**Pull request by wenkokke**
Caveats may apply.

Notably, this removes support for the path/command flags and requires that the scripts are run from the repository root.

I'm happy to restore support for the path/command flags and permit the commands to work from any directory, but figured I shouldn't complicate these files if that was unused complexity.

### CODE REVIEW

**Review by jorisdral — APPROVED** [review]
LGTM! And it's also nice that it now prints the files that are checked/formatted

**Comment by jorisdral** [comment]
FYI, to make CI pass these lines have to be modified to call the renamed formatting scripts:
https://github.com/IntersectMBO/lsm-tree/blob/c361efb779c0dc3c8998f7c0106462353fb012f3/.github/workflows/haskell.yml#L274
https://github.com/IntersectMBO/lsm-tree/blob/c361efb779c0dc3c8998f7c0106462353fb012f3/.github/workflows/haskell.yml#L212

**Review by mheinzel — APPROVED** [review]
Nice!

**Comment by wenkokke** [comment]
I've back ported some added robustness from a different project that checks for unstaged files and checks for the formatter versions.

**Review by jorisdral — APPROVED** [review]
LGTM again. Let's squash the commits a bit before we merge

**Comment by mheinzel** [comment]
Seems like something went wrong when rebasing, GitHub thinks you're adding 39 new commits.

**Pull request merged**
