### PR TITLE
Bump `io-classes` dependency to `1.6` and `1.7`

### PR DESCRIPTION
**Pull request by jorisdral**

### CODE REVIEW

**Comment by jorisdral** [comment]
We should merge #396 first

**Comment by jorisdral** [comment]
> We should merge #396 first

Alright, there are actually no conflicts, so this PR can be reviewed

**Review by dcoutts — APPROVED** [review]
LGTM!

**Review by recursion-ninja — APPROVED** [review]
Also looks good to me.

I like that `io-classes` consolidated `strict-mvar` and `strict-stm` into sub-libraries

**Pull request merged**
