### PR TITLE
Restructure `cabal.project` and clarify warning when benchmarking in debug mode

### PR DESCRIPTION
**Pull request by wenkokke**
This PR makes the following changes:

- Restructures `cabal.project` into `cabal.project.release` and `cabal.project.debug` so that we can switch between release/debug builds from the command line rather than by editing a file.
- Clarifies and unifies the warning printed when running a benchmark in debug mode.

This is to avoid the need to `git stash/apply` when switching branches, and to enable an entirely programmatic `git bisect` for benchmarks.

### CODE REVIEW

**Comment by jorisdral** [comment]
https://github.com/IntersectMBO/lsm-tree/blob/2e76991bc761a41ac579db324d9199588aa3460d/bench/macro/lsm-tree-bench-lookups.hs#L132 and https://github.com/IntersectMBO/lsm-tree/blob/2e76991bc761a41ac579db324d9199588aa3460d/bench/macro/lsm-tree-bench-bloomfilter.hs#L68 also have these messages, could you change them there too?

**Comment by wenkokke** [comment]
> https://github.com/IntersectMBO/lsm-tree/blob/2e76991bc761a41ac579db324d9199588aa3460d/bench/macro/lsm-tree-bench-lookups.hs#L132
> 
> and
> https://github.com/IntersectMBO/lsm-tree/blob/2e76991bc761a41ac579db324d9199588aa3460d/bench/macro/lsm-tree-bench-bloomfilter.hs#L68
> 
> also have these messages, could you change them there too?

Should this warning not be in all benchmarks?

**Comment by jorisdral** [comment]
> > https://github.com/IntersectMBO/lsm-tree/blob/2e76991bc761a41ac579db324d9199588aa3460d/bench/macro/lsm-tree-bench-lookups.hs#L132
> > 
> > and
> > https://github.com/IntersectMBO/lsm-tree/blob/2e76991bc761a41ac579db324d9199588aa3460d/bench/macro/lsm-tree-bench-bloomfilter.hs#L68
> > 
> > also have these messages, could you change them there too?
> 
> Should this warning not be in all benchmarks?



> > https://github.com/IntersectMBO/lsm-tree/blob/2e76991bc761a41ac579db324d9199588aa3460d/bench/macro/lsm-tree-bench-lookups.hs#L132
> > 
> > and
> > https://github.com/IntersectMBO/lsm-tree/blob/2e76991bc761a41ac579db324d9199588aa3460d/bench/macro/lsm-tree-bench-bloomfilter.hs#L68
> > 
> > also have these messages, could you change them there too?
> 
> Should this warning not be in all benchmarks?

Probably, though I think it is currently only missing from https://github.com/IntersectMBO/lsm-tree/blob/main/bench/macro/lsm-tree-bench-wp8.hs

**Review by jorisdral — APPROVED** [review]

**Review by dcoutts — APPROVED** [review]
LGTM

**Comment by wenkokke** [comment]
This probably should just use the existing `cabal-args` fields rather than defining a separate `cabal-project` field.

**Review by jorisdral — APPROVED** [review]
LGTM again. Let's squash the commits a bit before we merge

**Comment by wenkokke** [comment]
Breaking this up into two PRs due to staleness and squashing.

**Pull request closed without merging**
