### PR TITLE
Implement monoidal table API

### PR DESCRIPTION
**Pull request by mheinzel**
~~Depends on #314. Before un-drafting this, I want to make sure all the tests are enabled and run successfully.~~

As a bonus, the `Internal` module now doesn't know anything about the normal/monoidal distinction. We prevent opening a normal snapshot as monoidal through the labels (although we might iterate on the exact design of that).

I haven't touched any of the TODOs from #314 yet, we should first discuss what we want to do there.

The tests all seem to be enabled now, unless I missed something.

### CODE REVIEW

**Comment by jorisdral** [comment]
Just a quick remark that you should probably enable some of the monoidal class tests manually, because currently they pass the `expectFailure`s with the error `ErrExpectedMonoidalTable`

**Comment by mheinzel** [comment]
Yes, that's what I mean by making sure the tests are enabled.

**Review by jorisdral — COMMENTED** [review]
LGTM!

> I haven't touched any of the TODOs from https://github.com/IntersectMBO/lsm-tree/pull/314 yet, we should first discuss what we want to do there.

Could you maybe list here which TODOs those are?

**Review by jorisdral — APPROVED** [review]

**Comment by mheinzel** [comment]
> Could you maybe list here which TODOs those are?

There are a few open questions about `ResolveValue`:

- revisit totality requirement
- potentially move it to another module
- potentially add `SerialiseValue` as a superclass

**Pull request merged**
