### PR TITLE
Fix #350 by properly cleaning up RunBuilders in tests

### LINKED ISSUE #350: [BUG] `RunBuilder` tests take multiple minutes on Windows
**Describe the bug**
`RunBuilder` tests take multiple minutes on Windows

**Expected behavior**
Running times for the `RunBuilder` tests should be the same on Linux and MacOS as on Windows.

**Output**
CI output: https://github.com/IntersectMBO/lsm-tree/actions/runs/10515089091/job/29134408774#step:16:1220

**Desktop (please complete the following information):**
 - OS: Windows
 - GHC: all

### PR DESCRIPTION
**Pull request by jorisdral**
# Description

Resolves #350

# Checklist

- [x] Read our contribution guidelines at [CONTRIBUTING.md](https://github.com/IntersectMBO/lsm-tree/blob/main/CONTRIBUTING.md), and make sure that this PR complies with the guidelines.

### CODE REVIEW

**Comment by mheinzel** [comment]
If we ran these tests in a MockFS, we could assert that all handles get closed properly. Would be sensible to do, maybe in addition to the real FS ones?

**Comment by jorisdral** [comment]
> If we ran these tests in a MockFS, we could assert that all handles get closed properly. Would be sensible to do, maybe in addition to the real FS ones?

Good idea. I've added the check. Maybe we can use `withSimHasFS` in other places as well

**Review by dcoutts — COMMENTED** [review]
Looks ok but in the first patch I don't see what is the fix for #350. What actual change are we making, why does that fix the running time problem on Windows?

**Comment by jorisdral** [comment]
> Looks ok but in the first patch I don't see what is the fix for #350. What actual change are we making, why does that fix the running time problem on Windows?

I'm not so sure why the fix works, but what is clear is that the `RunBuilder` tests were leaking file descriptors, and it *looks* like that leak was causing a slowdown (or it's a spurious correlation, I don't really have a way to check)

**Review by dcoutts — APPROVED** [review]

**Pull request merged**
