### PR TITLE
Add run number field to TableContent

### PR DESCRIPTION
**Pull request by phadej**
Also add TODO to change the reprentation of closed table handle these should not need to have any `TableContent`.

### CODE REVIEW

**Review by dcoutts — APPROVED** [review]
Looks reasonable to me.

And I agree it'd be nice for a closed table to contain less.

**Comment by jorisdral** [comment]
I'm not sure I understand the TODO, is the current definition of `TableHandleState` not already doing what the TODO describes?

**Comment by phadej** [comment]
@jorisdral maybe, but not 100% as emptyTableContent is used. See https://github.com/IntersectMBO/lsm-tree/blob/6d075bd19af82be96c63a39e705448c4affcd21a/src/Database/LSMTree/Internal.hs#L552

**Review by jorisdral — APPROVED** [review]
LGTM as well -- just needs a rebase to fix a merge conflict

**Review by dcoutts — APPROVED** [review]

**Comment by phadej** [comment]
Rebased, make the field strict (now as its possible).

**Pull request merged**
